### ISSUE TITLE
provide a binary cache

### ISSUE THREAD

**Issue by erahhal** [nix-community/authentik-nix#23] opened 2024-04-24 16:10 UTC
Trying this out and it's taking over an hour to build. Is that expected? Is there a cache available for this?

**Comment by WilliButz** [comment] 2024-04-27 19:31
It does indeed take a considerable amount of time to build all combined (python / golang / node) dependencies, so it is expected.

Currently there is no cache available but a while back I was thinking about integrating [cachix](https://www.cachix.org/pricing) via github actions but I haven't gotten around to it.

**Comment by erahhal** [comment] 2024-04-27 20:20
In any case, it's working great for me. Thanks for the effort!

**Comment by WilliButz** [comment] 2024-07-12 11:24
Some weeks back I tried to solve this via the nix-community CI infra that makes use of buildbot and cachix.
That didn't work because for some reason buildbot's nix-eval-jobs failed when trying to evaluate the check outputs with the VM test.
While regular `nix build` is completely fine with the flake outputs here, I could reproduce the evaluation error locally with nix-eval-jobs. Not sure what's going on, as I didn't investigate further but I'd be happy if someone is interested in further debugging what's going on there :)

**Comment by zowoq** [comment] 2024-08-03 10:40
@WilliButz I couldn't reproduce the nix-eval-jobs error locally and we don't have the logs of the previous error so I tried testing it on buildbot, it finished evaluating and starts building the vm tests: https://buildbot.nix-community.org/#/builders/2684/builds/2.

**Comment by WilliButz** [comment] 2024-08-03 12:43
Huh interesting, not sure what changed, as it definitely did fail to evaluate some months ago :thinking: 
(I suppose you re-added the label to the project here?)

Thank you! :)

**Comment by zowoq** [comment] 2024-08-04 00:25
I tried the previous commits that github has marked as failing and I still can't reproduce a nix-eval-jobs error. Not sure what the problem was as I'd have expected a bug in the nix-eval-jobs used by CI is using would be causing problems beyond this repo.

> (I suppose you re-added the label to the project here?)

Yes, needed the label to start the CI job.

If you have any other problems with the CI feel free to ping me.

**Closed** 2024-08-22 21:35 UTC

**Comment by erahhal** [comment] 2024-08-23 03:14
Awesome, thanks!
